---
title: "Client Report - What's in a name?"
subtitle: "Course DS 250"
author: "Carter Baumgart"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

_Christian names seem to be on the decline while other names seem to take turns having spikes and fall offs. A much more comprehensive analysis would need to be done to find further trends and to identify why certain names increase or decrease in popularity._

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```

__How does your name at your birth year compare to its use historically?__

My name is in higher usage than previous years, and in general is a part of an upswing in the use of the name Carter overall.

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here

oliver_data = df[(df['name'] == 'Oliver') & (df['UT'] == 'Utah')]
total_births = oliver_data['Total'].sum()
chart = px.line(oliver_data, x='year', y='Total', title='Frequency of Oliver in Utah',
                labels={'year': 'Year', 'Total': 'Births'},
                line_shape='linear', color='name')
chart.show()


"""carter_data = df[(df['name'] == 'Oliver') & (df['UT'] == 'Utah')]

chart = px.line(carter_data, x='year', y='Total', title='Frequency of Oliver in Utah',
              labels={'year': 'Year', 'Total': 'Births'},
              line_shape='linear', color='name')

chart.show()"""
```

The usage of Carter increased significantly starting in 1994

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

My guess would be that they were 33 years old since the most common year of Brittany was 1990, and I wouldn't guess that they were older than 41 or younger than 22.

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here

brittany_table = (df
    .groupby(['name', 'year'])
    .sum().query('name == "Brittany"')
    .reset_index().filter(['name', 'year', 'Total'])
    .sort_values('Total'))

chart = px.bar(brittany_table, x='year', y='Total', title='Brittany Total over the Years',
             labels={'Total': 'Total Value'}, text='Total', height=600)

chart.show()
```

THe most common range of Brittany falls between 1982 and 2001, peaking 1990

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

The usage of all four names decreased significantly around the 1970s. The usage of Mary was also much higher previous to the 1970s than any of the other names.

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here
mmpp_table = (df
    .groupby(['name', 'year'])
    .sum().query('name == "Mary" | name == "Martha" | name == "Peter" | name == "Paul"')
    .reset_index().filter(['name', 'year', 'Total'])
    .sort_values('Total'))

# Filter for the years 1920-2000
mmpp_table = mmpp_table[(mmpp_table['year'] >= 1920) & (mmpp_table['year'] <= 2000)]

chart = px.scatter(mmpp_table, x='year', y='Total', color='name',
                   title='Names Total over the Years (1920-2000)',
                   labels={'Total': 'Total Value'}, height=600)

chart.show()
```

Christian names spiked post WWII but quickly fell off again

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

It doesn't look like the usage of the name Harry increased during the time when the first Harry Potter movie was released.

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here

harry_data = df[df['name'] == 'Harry']

chart = px.line(harry_data, x='year', y='Total', title='Frequency of Harry',
              labels={'year': 'Year', 'Total': 'Births'},
              line_shape='linear', color='name')

chart.add_shape(dict(type="line", x0=2001, x1=2001, y0=0, y1=max(harry_data['Total']),
                   line=dict(color="black", dash="dash")))

chart.add_annotation(x=2001, y=max(harry_data['Total']), text="Release Year (2001)",
                   showarrow=True, arrowhead=4, ax=0, ay=-40)

chart.show()

```

Harry Potter had no noticeable influence on the steady decline of the usage of the name Harry.

